name: CI

on: push

jobs:
  lua:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - name:  Install libreadline
        run: |
          sudo apt-get install -y libreadline-dev

      - name: Install Lua
        run: |
          pip install git+https://github.com/luarocks/hererocks
          hererocks lua_install -r^ --luajit=2.1

      - name: Run tests
        run: |
          source lua_install/bin/activate
          luarocks install lrexlib-pcre2 --verbose
          luarocks install lrexlib-pcre2 2.9.2-1 --verbose
          luarocks install lrexlib-pcre2 2.9.1-1 --verbose
          busted --verbose
